.babelrc
app.js
package-lock.json
package.json
public/index.html
routes/welcome.js

**What does this PR do?**
1. A basic express server for ballers, with a single endpoint at `GET /api/v1/welcome` returning 
```
{
success: true,
message: 'Welcome to Ballers API endpoint'
}
```
2. Setup babel to transpile ES6 written code to ES5
3. Link repo to heroku

#171565994 setup express server and welcome endpoint

---

.babelrc
.nycrc
.travis.yml
README.md
package-lock.json
package.json

This PR configures coveralls for ballers
Coveralls ensure that we deliver better code. It ensures that we can see the part of the codebase not covered by the test. The current setup is set to reject codes with less than 80% coverage.
* Install the new packages with `npm install`
* Run `npm test` on your local machine (This should run the test and show the coverage).

#171808802 Configure coveralls for ballers

---

.eslintrc
.eslintrc.js
.hound.yml

This PR configures HoundCI for ballers
HoundCI is an automated code review for GitHub pull requests. It will comment on code quality, allowing us to maintain a clean codebase.
This cannot be tested locally since it is an automated code review for GitHub Pull Requests. However, when a PR is created, HoundCI will check the code quality of the PR as shown below:

#171808808 Configure HoundCI for ballers

---

.eslintrc
.prettierrc
package-lock.json
package.json
server/config/winston.js
server/models/user.model.js
server/routes/user.js
test/config.js
test/routes/user.test.js

This PR refactors linting in the codebase.
Each of the tasks is done in a different commit for easy review:
* Fix Hound eslint parser error
* Configure Prettier to work with eslint (for visual studio code)
* Setup Husky for eslint and prettier
* Hound will not display the `parser error` any more
* On Visual studio code, installing the prettier plugin will no longer conflict with our eslint styles
* Husky will run when you try to commit a file. The staged files will be automatically prettified by prettier and eslint will try to fix any eslint errors (automatically) or print them out so that they can be fixed by you.

#172016511 Refactor linting in the codebase

---

server/controllers/user.controllers.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/services/user.service.test.js

Add login endpoint
Add login endpoint for user authentication
Visit `/api/v1/user/login`
Parameters `email` `password`
#172045791

#172045791 Login endpoint

---

.env.sample
mailer/index.js
package-lock.json
package.json
server/controllers/user.controllers.js
server/models/user.model.js
server/services/mailer.service.js
test/config.js
test/controllers/user.controller.test.js
test/services/mailer.service.test.js

This PR sends mail (using the mailer template in Part 1 - https://github.com/Highrachy/ballers-api/pull/17) when a user creates an account. An email is sent to the user email address in production by using the SendGrid API and sent to MailTrap in other environments.
1. Send email via SendGrid API
2. Send email to MailTrap by using nodemailer
3. Send mail when user registers a new account
4. Update test coverage to 100%.
1. Check out into this branch
2. Run `npm install` to update dependencies
3. Start the API server on your local machine `npm run start:dev`
4. Visit `http://localhost:3000/api/v1/user/register` and create a new user
5. An email will be sent to our MailTrap account.
6. Click on the Text tab in MailTrap to view the equivalent mail in text format.
6. You can update the …

#172304633 Send email via MailTrap and SendGrid [User Activation  - Part 2]

---

server/controllers/user.controllers.js
server/models/user.model.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/config.js
test/controllers/user.controller.test.js
test/services/user.service.test.js

This PR activates a user account.
1. Creates the user activation route - `http://localhost:3000/api/v1/user/activate?token=`
2. Update login function in user service
3. Create activate user service to activate user account
4. Update the API documentation.
1. Check out into this branch
2. Run `npm install` to update dependencies
3. Start the API server on your local machine `npm run start:dev`
4. Create a new user via the register user endpoint
5. Copy the token and visit `http://localhost:3000/api/v1/user/activate?token=COPIED_TOKEN_HERE` to activate the account

#172304633 User account activation [User Activation - Part 3]

---

server/controllers/user.controllers.js
server/helpers/middleware.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/services/user.service.test.js

Add edit user endpoint for dashboard
Create endpoint to edit a user
`PUT /api/v1/user/update`
Sample data
`{
"firstName": "User Firstname",
"lastName": "User Lastname",
"phone": "08012345678"
}`
All requests should be sent with token as header `Authorization`
#173766649

#173766649 edit user endpoint

---

server/models/property.model.js
server/schemas/property.schema.js
test/controllers/property.controller.test.js
test/factories/property.factory.js

Add document title to property schema
Add document title to property schema. So as to add document to prove authenticity of land ownership.
`POST /api/v1/property/add`
`PUT /api/v1/property/update`
`titleDocument: string(url to watermarked document)`
#173915847

#173915847 add document title to property schema

---

server/controllers/user.controllers.js
server/routes/user.routes.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/services/user.service.test.js

Add admin to view users endpoint
Add an endpoint to allow admin see all registered users
`GET /api/v1/user/view-users`
`Authorization {token}`
#174250358

#174250358 admin to view users endpoint

---

server/controllers/user.controllers.js
server/models/user.model.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/services/user.service.test.js

`PUT /api/v1/user/update/preferences`
`{
"preferences": {
"type": "3 bedroom apartment",
"location": "lekki phase 1",
"minPrice": 10000000,
"maxPrice": 20000000
}
}`
#174250276

#174250276 update user model and endpoints

---

server/controllers/property.controllers.js
server/routes/property.routes.js
server/services/property.service.js
test/controllers/property.controller.test.js

Streamline Search endpoint.
Streamline Search endpoint to get distinct states & house types
`GET /api/v1/property/available`
#174466910

#174466910 streamline search endpoint 

---

server/controllers/paymentPlan.controllers.js
server/models/paymentPlan.model.js
server/models/property.model.js
server/routes/index.js
server/routes/paymentPlan.routes.js
server/schemas/paymentPlan.schema.js
server/schemas/property.schema.js
server/schemas/user.schema.js
server/services/paymentPlan.service.js
server/services/property.service.js
test/controllers/paymentPlan.controller.test.js
test/factories/paymentPlan.factory.js
test/services/paymentPlan.service.test.js
test/services/property.service.test.js

Add payment plan endpoints
add endpoints for admin to create, view and delete payment plans
`POST /api/v1/payment-plan/add`
`{
"planName": "monthly",
"planDescription": "monthly payment plan",
"paymentFrequency": 1
}`
`GET /api/v1/payment-plan/all`
`DELETE /api/v1/payment-plan/delete/:id`
#174250315

#174250315 add payment plan

---

server/controllers/transaction.controllers.js
server/models/transaction.model.js
server/routes/index.js
server/routes/transaction.routes.js
server/schemas/transaction.schema.js
server/services/transaction.service.js
test/controllers/transaction.controller.test.js
test/factories/transaction.factory.js
test/services/transaction.service.test.js

Add transaction model and endpoint
Create transaction model and endpoint to record transactions
`GET /api/v1/transaction/all`
`POST /api/v1/transaction/add`
#174250297

#174250297 add transaction model

---

server/models/visitation.model.js
server/schemas/visitation.schema.js
test/controllers/visitation.controller.test.js
test/factories/visitation.factory.js

Add date of visitation to Visitation schema
Add date of visitation to Visitation schema
`POST /api/v1/visitation/schedule`
#174571227

#174571227 add date of visitation

---

server/helpers/errorHandler.js
server/helpers/uploadImage.js
server/routes/user.routes.js
test/services/paymentPlan.service.test.js
test/services/property.service.test.js
test/services/user.service.test.js

This PR fixes the associated error of uploading large image to Cloudinary
- Improve error handler
- Enable user to upload image with 1MB Limit
`POST /user/upload-image`
https://github.com/Highrachy/ballers-api/pull/41
#174717678

#174717678 Fix large image error

---

server/controllers/enquiry.controllers.js
server/routes/enquiry.routes.js
server/services/enquiry.service.js
test/controllers/enquiry.controller.test.js
test/services/enquiry.service.test.js

This PR loads a single enquiry.
Have the get single enquiry endpoint working:
`GET /enquiry/:id`
Test in Postman

#173915841 Get single property enquiry endpoint

---

test/controllers/enquiry.controller.test.js
test/controllers/paymentPlan.controller.test.js
test/controllers/property.controller.test.js
test/controllers/transaction.controller.test.js
test/controllers/user.controller.test.js
test/controllers/visitation.controller.test.js

Fix tests structure
Update all tests and ensure that all before each are inside a describe block
`npm run test`

fix tests structure

---

server/services/enquiry.service.js
test/controllers/enquiry.controller.test.js
test/controllers/offer.controller.test.js
test/services/offer.service.test.js

Prevent user from making more than one enquiry per property
Add functionality to add enquiry endpoint to prevent user from making more than one enquiry per property
`POST /api/v1/enquiry/add`

prevent user from making more than one enquiry per property

---

server/config/index.js
server/controllers/mailer.controllers.js
server/controllers/referral.controllers.js
server/controllers/user.controllers.js

This PR creates a dynamic mailer link when a mail is sent to the user
Update all existing email link to a dynamic link
- Register a new account on your localhost
- Email link should point to localhost instead of ballers.ng
None
#175110678

#175110678 Create dynamic mailer link

---

server/services/referral.service.js

This PR adds referral code to referral invite response
- Add referral code to referral invite response
`GET /referral/:id`
None
None

#175110678 Add referral code to referral invite

---

server/models/transaction.model.js
server/schemas/transaction.schema.js
test/controllers/transaction.controller.test.js
test/factories/transaction.factory.js
test/services/transaction.service.test.js

Add offer id to transaction model
Add offer id to transaction model
#175160638

#175160638 add offer id to transaction model

---

server/controllers/user.controllers.js
server/routes/user.routes.js
server/services/offer.service.js
server/services/referral.service.js
server/services/transaction.service.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/services/user.service.test.js

Add account overview endpoint
Add endpoint to return financial overview of user account 
`GET /api/v1/user/overview`
#175070987

#175070987 account overview endpoint

---

server/services/user.service.js
test/services/user.service.test.js

This PR fixes the registered referral status for a registered referee
- Update referee information to registered 
- Register with a valid referrer code
None
None

#175179088 Update registered referee status to registered after registration

---

mailer/index.js
server/controllers/offer.controllers.js
server/services/offer.service.js
test/controllers/offer.controller.test.js

Add function that sends mail to user when offer letter is accepted
Add function that sends mail to user when offer letter is accepted
`PUT /api/v1/offer/accept`
#175178861

#175178861 send mail to user when offer letter is accepted

---

mailer/index.js
server/controllers/user.controllers.js
test/controllers/user.controller.test.js

Send welcome mail to user when email is confirmed
Send welcome mail to user when email is confirmed
`GET api/v1/user/activate`
#175261549

#175261549 send welcome mail to user when email is confirmed

---

server/controllers/property.controllers.js
server/routes/property.routes.js
server/services/offer.service.js
server/services/property.service.js
test/controllers/property.controller.test.js

Add endpoints to load assigned properties which include additional information such as transactions and sums
Add endpoints to load assigned properties which include additional information such as transactions and sums
`GET /property/assigned`
`GET /property/assigned/:id`
#175070906

#175070906 load assigned properties endpoint

---

server/services/property.service.js
test/controllers/property.controller.test.js
test/factories/enquiry.factory.js
test/factories/offer.factory.js
test/factories/property.factory.js

This PR adds INTERESTED offer status to assigned properties
- add interested to assigned properties
```
GET /property/assigned
```
None
#175070906

#175070906 Add interested to assigned properties

---

server/services/referral.service.js
test/controllers/referral.controller.test.js

Fix referral mail link
Fix bug of undefined id in referral mail link
`POST /api/v1/referral/invite`
#175261521

#175261521 fix referral mail link

---

server/controllers/offer.controllers.js
server/routes/offer.routes.js
server/schemas/offer.schema.js
server/services/offer.service.js
test/controllers/offer.controller.test.js
test/services/offer.service.test.js

Modify endpoint to cancel offer letter
Allows an admin to cancel an offer letter
`PUT /api/v1/offer/cancel`
#175261605

#175261605 cancel offer letter

---

.travis.yml
server/services/mailer.service.js
test/controllers/offer.controller.test.js
test/controllers/referral.controller.test.js
test/controllers/user.controller.test.js
test/controllers/visitation.controller.test.js
test/services/mailer.service.test.js
test/services/offer.service.test.js

This PR fixes the failing tests on Travis CI
- stub mail service
- Use `osx` OS as the testing machine on Travis CI
A green check besides Travis shows that this is working as expected.
None
#175485862

Fix failing tests

---

server/services/offer.service.js
test/controllers/offer.controller.test.js

Sort and remove expired offers from active route
Sort and remove expired offers from active route
`GET /api/v1/offer/active`
#175261546

#175261546 sort and remove expired offers from active route

---

mailer/index.js
server/controllers/offer.controllers.js

Update all email contents
Update all email contents
`PUT /api/v1/offer/accept`
[Email templates](https://docs.google.com/presentation/d/1l9XZHtV9-uFomT5bjZF5AAcE7pcOq8WrHmFUvHOdSjc/edit?ts=5f55d6f2#slide=id.p)
#175335976

#175335976 update email content

---

server/helpers/constants.js
server/helpers/middleware.js

Adds middleware functions to test for vendor and content editor access privileges
Adds middleware functions to test for vendor and content editor access privileges
#175531363

#175531363 add content and vendor middleware

---

server/controllers/user.controllers.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js

Add routes to upgrade user to content editor and to downgrade content editor to user
Add routes to upgrade user to content editor and to downgrade content editor to user
`PUT api/v1/user/editor/upgrade`
`PUT api/v1/user/editor/downgrade`
#175531471

#175531471 upgrade or downgrade user to editor 

---

server/controllers/transaction.controllers.js
server/routes/transaction.routes.js
server/services/transaction.service.js
test/controllers/transaction.controller.test.js

Add endpoints to return all lists of contribution & referral reward transactions
Add endpoints to return all lists of contribution & referral reward transactions
`GET api/v1/transaction/user/contribution-rewards`
`GET api/v1/transaction/user/referral-rewards`
#175071019

#175071019 add contribution and referral rewards endpoints

---

server/models/area.model.js
server/models/contentProperty.model.js

Create content property model
Create content property model for properties used in property search and price estimation
NA
#175634783

#175634783 create content property model

---

server/controllers/user.controllers.js
server/helpers/pagination.js
server/routes/user.routes.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/factories/user.factory.js
test/helpers.js
test/services/user.service.test.js

Add pagination to `/api/v1/user/all` endpoint
Add pagination to `/api/v1/user/all` endpoint
`GET /api/v1/user/all?page=1&limit=1`
`page` is the page number. Default is `1`
`limit` is the amount of documents per page. Default is `10`
#175179054

#175179054 add pagination to all users endpoint

---

server/controllers/area.controllers.js
server/controllers/contentProperty.controllers.js
server/routes/area.routes.js
server/routes/contentProperty.routes.js
server/routes/index.js
server/schemas/area.schema.js
server/schemas/contentProperty.schema.js
server/services/area.service.js
server/services/contentProperty.service.js
test/controllers/area.controller.test.js
test/controllers/contentProperty.controller.test.js
test/factories/area.factory.js
test/factories/contentProperty.factory.js

Add routes to allow editor add content property
Add routes to allow editor add content property
`POST /api/v1/area/add`
`POST /api/v1/content-property/add`
#175634786

#175634786 add content property routes

---

server/controllers/contentProperty.controllers.js
server/routes/contentProperty.routes.js
server/schemas/contentProperty.schema.js
server/services/contentProperty.service.js
test/controllers/contentProperty.controller.test.js

Add routes to edit and delete properties
Add routes to edit and delete properties
`PUT /api/v1/content-property/update`
`DELETE /api/v1/content-property/delete/:id`
#175634788

#175634788 edit and delete property routes

---

server/controllers/area.controllers.js
server/controllers/contentProperty.controllers.js
server/routes/area.routes.js
server/routes/contentProperty.routes.js
server/services/area.service.js
server/services/contentProperty.service.js
test/controllers/area.controller.test.js
test/controllers/contentProperty.controller.test.js
test/factories/area.factory.js
test/factories/contentProperty.factory.js

Search for content property
Search for content property based on state, area & house type
`GET api/v1/area/`
`GET api/v1/area/:state`
`GET /api/v1/content-property/area/:id`
#175634790

#175634790 search for content property

---

server/controllers/area.controllers.js
server/routes/area.routes.js
server/schemas/area.schema.js
server/services/area.service.js
server/services/contentProperty.service.js
test/controllers/area.controller.test.js

Add routes to edit and delete area
Add routes to edit and delete area
`PUT /api/v1/area/update`
`DELETE /api/v1/area/delete/:id`
#175735116

#175735116 endpoints to update and delete area

---

server/controllers/contentProperty.controllers.js
server/routes/contentProperty.routes.js
server/services/contentProperty.service.js
test/controllers/contentProperty.controller.test.js

Retrieve searched content property for calculation
Retrieve searched content property for calculation
`GET /api/v1/content-property?areaId={areaId}& houseType={houseType}`
#175634791

#175634791 return properties info

---

server/controllers/contentProperty.controllers.js
server/helpers/pagination.js
server/routes/contentProperty.routes.js
server/services/contentProperty.service.js
server/services/user.service.js
test/controllers/contentProperty.controller.test.js
test/controllers/user.controller.test.js
test/helpers.js

List all properties & add pagination to `/api/v1/content-property/all` endpoint
List all properties & add pagination to `/api/v1/content-property/all` endpoint
`GET /api/v1/content-property/all?page=1&limit=1`
`page` is the page number. Default is `1`
`limit` is the amount of documents per page. Default is `10`
#175635136

#175635136 list all properties

---

server/controllers/area.controllers.js
server/routes/area.routes.js
server/services/area.service.js
test/controllers/area.controller.test.js
test/controllers/contentProperty.controller.test.js

Add route to list all areas
Add route to list all areas with number of properties under them with corresponding minimum, maximum & average values of properties 
`GET /api/v1/area/all`
#175735113

#175735113 add route to list all areas

---

server/routes/area.routes.js
server/routes/contentProperty.routes.js
test/controllers/area.controller.test.js
test/controllers/contentProperty.controller.test.js

Make routes for searching content properties public
Make routes for searching content properties public
`GET api/v1/area/states`
`GET api/v1/area/:state`
`GET /api/v1/content-property/area/:id`
`GET /api/v1/content-property?areaId={areaId}& houseType={houseType}`
#175845002

#175845002 make routes for searching content properties public

---

server/controllers/area.controllers.js
server/controllers/contentProperty.controllers.js
server/routes/area.routes.js
server/routes/contentProperty.routes.js
server/services/area.service.js
server/services/contentProperty.service.js
server/services/property.service.js
test/controllers/area.controller.test.js
test/controllers/contentProperty.controller.test.js

Add routes to return single content property and area
Add routes to return single content property and area
`GET /api/v1/content-property/:id`
`GET /api/v1/area/:id`
#175846239

#175846239 add routes to return single content property and area

---

server/controllers/user.controllers.js
server/models/user.model.js
server/schemas/user.schema.js
server/services/mailer.service.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/services/user.service.test.js

Add vendor object to user model
Add vendor object to user model
NA
[Slides](https://docs.google.com/presentation/d/1z9UGMG_RK7okhGxkhpyeam36cZcZeXzMg0291QYxXLs/edit?ts=5fb76306#slide=id.ga26e5542d0_0_50)
#175634768

#175634768 add vendor object to user model

---

server/controllers/area.controllers.js
server/services/area.service.js
test/controllers/area.controller.test.js

Prevent return of areas without content properties
Prevent return of areas without content properties
`GET api/v1/area/state/{state}`
#175868569

#175868569 prevent return of areas without content properties

---

server/controllers/user.controllers.js
server/models/user.model.js
server/routes/user.routes.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/helpers.js

Load vendor info for verification
Load vendor info for verification
`GET /api/v1/user/vendor/all`
#175928810

#175928810 load vendor info for verification

---

server/controllers/user.controllers.js
server/helpers/constants.js
server/models/user.model.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/helpers.js

Allow admin to approve vendor information
Allow admin to approve vendor information
`PUT /api/v1/user/vendor/verify`
`PUT /api/v1/user/vendor/verify/comment`
`PUT /api/v1/user/vendor/verify/step`
#175634775

#175634775 allow admin to approve vendor information

---

server/controllers/user.controllers.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js

Allows a  vendor to update their information for verification
Allows a  vendor to update their information for verification
#175634772

#175634772 vendor update information for verification

---

server/controllers/visitation.controllers.js
server/helpers/pagination.js
server/models/visitation.model.js
server/routes/visitation.routes.js
server/services/contentProperty.service.js
server/services/user.service.js
server/services/visitation.service.js
test/controllers/user.controller.test.js
test/controllers/visitation.controller.test.js
test/factories/visitation.factory.js
test/helpers.js
test/services/visitation.service.test.js

Update visitation schedule for vendor
Update visitation schedule for vendor
`POST /api/v1/visitation/schedule`
#176029266

#176029266 update visitation for vendor

---

server/helpers/constants.js
server/models/enquiry.model.js
server/models/property.model.js
server/models/user.model.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/factories/address.factory.js

Fix vendor model
1. Add verification step for identification.
2. Make company address have (state, city, street).
3. Add bank object.
`PUT /api/v1/user/vendor/verify`
`PUT /api/v1/user/vendor/verify/step`
#176136506

#176136506 fix vendor model

---

server/models/user.model.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js

Fix vendor account update bug
Fix vendor account update bug
`PUT api/v1/user/vendor/update`
#176268205

#176268205 update vendor personal user info

---

server/controllers/user.controllers.js
server/routes/user.routes.js
server/services/user.service.js
test/controllers/user.controller.test.js

Add route to get single user
Add route to get single user
`GET /api/v1/user/:id`
#176337684

#176337684 add route to get single user

---

server/controllers/user.controllers.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/offer.controller.test.js
test/controllers/user.controller.test.js
test/controllers/visitation.controller.test.js
test/helpers.js

Add routes to edit & remove directors or signatories
Add routes to edit & remove directors or signatories
`PUT /api/v1/user/vendor/director/add`
`DELETE /api/v1/user/vendor/director/remove/:id`
#176337881

#176337881 edit & remove directors or signatories

---

server/helpers/middleware.js
server/routes/user.routes.js
test/controllers/enquiry.controller.test.js
test/controllers/offer.controller.test.js
test/controllers/property.controller.test.js
test/controllers/transaction.controller.test.js
test/controllers/user.controller.test.js
test/controllers/visitation.controller.test.js
test/helpers.js

Update middleware to support verified & unverified vendors
Update middleware to support verified & unverified vendors
#176409047

#176409047 update middleware to support verified & unverified vendors

---

server/controllers/enquiry.controllers.js
server/models/enquiry.model.js
server/routes/enquiry.routes.js
server/services/enquiry.service.js
server/services/offer.service.js
test/controllers/enquiry.controller.test.js
test/controllers/offer.controller.test.js
test/controllers/property.controller.test.js
test/services/enquiry.service.test.js
test/services/offer.service.test.js

Make enquiries support vendor
Make enquiries support vendor
#176408984

#176408984 make enquiries support vendor

---

mailer/index.js
server/controllers/offer.controllers.js
server/controllers/referral.controllers.js
server/controllers/user.controllers.js
test/controllers/user.controller.test.js

Update email template
Update email template
[Slides](https://docs.google.com/presentation/d/1l9XZHtV9-uFomT5bjZF5AAcE7pcOq8WrHmFUvHOdSjc/edit?ts=5f55d6f2#slide=id.ga54090c310_0_7)
#176430728

#176430728 update email template

---

server/models/user.model.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js

Add in review for vendor update
Add in review for vendor update
#176454677

#176454677 add in review for vendor update

---

server/controllers/user.controllers.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js

Ensure users can submit empty and null values for user schema
Ensure users can submit empty and null values for user schema
`PUT /api/v1/user/update`
#176430738

#176430738 Ensure users can submit empty and null values for user schema

---

server/controllers/user.controllers.js
server/models/user.model.js
server/routes/user.routes.js
server/services/user.service.js
test/controllers/user.controller.test.js

Add vendor certification for lawyer verification
Add vendor certification for lawyer verification
`PUT /api/v1/user/vendor/certify`
#176454681

#176454681 add vendor certification for lawyer verification

---

server/controllers/user.controllers.js
server/helpers/constants.js
server/models/user.model.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js

Resolve all comments when admin verifies step
Resolve all comments when admin verifies step
`PUT /api/v1/user/vendor/verify/step`
#176533738

#176533738 resolve all comments when admin verifies step

---

server/controllers/user.controllers.js
server/helpers/middleware.js
server/models/user.model.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js

Add endpoints to enable an admin ban or unban a user
Add endpoints to enable an admin ban or unban a user
`PUT /api/v1/user/ban`
`PUT /api/v1/user/unban`
#176533745

#176533745 add routes to ban and unban user

---

server/services/user.service.js
test/controllers/user.controller.test.js

Update sensitive and non-sensitive info for vendor
Update sensitive and non-sensitive info for vendor
#176630414

#176630414 update sensitive and non sensitive info for vendor

---

mailer/index.js
server/controllers/user.controllers.js
test/controllers/user.controller.test.js

Send email to banned and unbanned user
Send email to banned and unbanned user
`PUT /api/v1/user/ban`
`PUT /api/v1/user/unban`
#176630166

#176630166 send email to banned and unbanned user

---

server/models/user.model.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/factories/vendor.factory.js

Add what changed to vendor verification
Add what changed to vendor verification to help admin identify updated fields
`PUT /api/v1/user/vendor/verify`
#176630115

#176630115 add what changed to vendor verification

---

server/controllers/offer.controllers.js
server/controllers/property.controllers.js
server/routes/offer.routes.js
server/services/offer.service.js
server/services/property.service.js
test/controllers/offer.controller.test.js
test/controllers/user.controller.test.js
test/services/offer.service.test.js
test/services/user.service.test.js

Fix pending offer  endpoints in admin/vendor sheets
Fix pending endpoints in admin/vendor sheets
#176630188

#176630188 fix pending offer endpoints in admin/vendor sheets

---

mailer/index.js
server/controllers/user.controllers.js
test/controllers/user.controller.test.js

Send email to vendor when account is verified or certified
Send email to vendor when account is verified or certified
`PUT /api/v1/user/vendor/certify`
`PUT /api/v1/user/vendor/verify`
#176735787

#176735787 send email to vendor when account is verified or certified

---

server/helpers/dates.js
server/services/user.service.js
test/controllers/user.controller.test.js

Add timestamp to log date
Add timestamp to log date
#176735767

#176735767 add timestamp to log date

---

server/helpers/projectedSchemaInfo.js
server/services/enquiry.service.js
server/services/offer.service.js
test/controllers/enquiry.controller.test.js
test/controllers/offer.controller.test.js
test/controllers/property.controller.test.js
test/factories/vendor.factory.js
test/helpers.js

Return vendor info for enquiry & offer endpoints
Return vendor info for enquiry & offer endpoints
`GET /api/v1/enquiry/all`
`GET /api/v1/enquiry/:id`
`GET /api/v1/offer/all`
`GET /api/v1/offer/active`
`GET /api/v1/offer/user/:id`
#176735777

#176735777 return vendor info for enquiry & offer endpoints

---

mailer/index.js
server/controllers/visitation.controllers.js
server/helpers/constants.js
server/helpers/dates.js
server/helpers/funtions.js
server/helpers/middleware.js
server/models/visitation.model.js
server/routes/visitation.routes.js
server/schemas/visitation.schema.js
server/services/visitation.service.js
test/controllers/visitation.controller.test.js

Add routes to reschedule and resolve visitations
Add routes to reschedule and resolve visitations
`PUT /api/v1/visitation/cancel`
`PUT /api/v1/visitation/reschedule`
`PUT /api/v1/visitation/resolve`
#176843012

#176843012 add more processes for visitation

---

.github/pull_request_template.md

The purpose of this PR is to create a default pull request template.
Created a default pull request template
This can be tested by...
#176917191
None

Create a default pull request template

---

package-lock.json
server/models/user.model.js
server/schemas/user.schema.js
test/config.js
test/controllers/area.controller.test.js
test/controllers/contentProperty.controller.test.js
test/controllers/enquiry.controller.test.js
test/controllers/offer.controller.test.js
test/controllers/paymentPlan.controller.test.js
test/controllers/property.controller.test.js
test/controllers/referral.controller.test.js
test/controllers/transaction.controller.test.js
test/controllers/user.controller.test.js
test/controllers/visitation.controller.test.js
test/services/enquiry.service.test.js
test/services/offer.service.test.js
test/services/paymentPlan.service.test.js
test/services/property.service.test.js
test/services/referral.service.test.js
test/services/transaction.service.test.js
test/services/user.service.test.js
test/services/visitation.service.test.js

The purpose of this PR is to add profile image to user/updates to fit in with the S3 implementation
- Update user/update endpoint
- Depreacate `useDatabase`
This can be tested by making a request to `/user/update`
#176917304 
None

#176917304  Update profile image endpoint

---

server/helpers/filters.js
server/services/user.service.js
test/controllers/user.controller.test.js

The purpose of this PR is to...
Have the following working...
`GET /api/v1/user/?sortBy=[parameter]&sortDirection=[asc/desc]`
#176842968

#176842968 add sort to `/user/all` endpoint

---

server/helpers/filters.js
test/controllers/user.controller.test.js
test/helpers.js

Add range to filters
Add range to filters
equals `/api/v1/route/all?parameter=value`
to `/api/v1/route/all?parameter=0_:_value`
from `/api/v1/route/all?parameter=value_:_0`
range `/api/v1/route/all?parameter=from_:_to`
#176955810

#176955810 add range to filters

---

server/helpers/filters.js
server/models/offer.model.js
server/schemas/offer.schema.js
server/services/offer.service.js
test/controllers/offer.controller.test.js
test/factories/offer.factory.js
test/services/offer.service.test.js

Generate next payment dates for offer
Generate next payment dates for offer
`POST /api/v1/offer/create`
#176955705

#176955705 generate next payment dates for offer

---

server/controllers/offer.controllers.js
server/helpers/constants.js
server/models/nextPayment.model.js
server/models/offer.model.js
server/schemas/offer.schema.js
server/services/nextpayment.service.js
server/services/offer.service.js
test/controllers/offer.controller.test.js
test/factories/offer.factory.js
test/services/offer.service.test.js

Add nextPayment schema
Add nextPayment schema
NA
#176955705

#176955705 add next payment schema

---

server/controllers/property.controllers.js
server/helpers/constants.js
server/models/property.model.js
server/routes/property.routes.js
server/schemas/property.schema.js
server/services/property.service.js
test/controllers/property.controller.test.js
test/factories/property.factory.js
test/helpers.js

Update neighborhood for properties
Update neighborhood for properties
`POST /api/v1/property/add`
#176955779

#176955779 update neighborhood for properties

---

server/controllers/property.controllers.js
server/models/property.model.js
server/routes/property.routes.js
server/schemas/property.schema.js
server/services/property.service.js
test/controllers/property.controller.test.js
test/factories/property.factory.js
test/helpers.js

Implement gallery functionality for property
Implement gallery functionality for property
`POST /api/v1/property/:propertyId/gallery`
`PUT /api/v1/property/:propertyId/gallery`
`DELETE /api/v1/property/:propertyId/gallery`
#176955804

#176955804 implement gallery functionality for property

---

server/helpers/filters.js
server/helpers/projectedSchemaInfo.js
server/models/property.model.js
server/schemas/property.schema.js
server/services/property.service.js
test/controllers/property.controller.test.js
test/factories/property.factory.js
test/helpers.js

The purpose of this PR is to add `features` property to the property model
Have the following working
* Add `features` property
* Update `timeAwayFromProperty` to `distance`
GET `/api/v1/property/add`
#177149496

#177149496 Add features property to property model

---

server/controllers/reportedProperty.controllers.js
server/helpers/filters.js
server/models/reportedProperty.model.js
server/routes/index.js
server/routes/reportedProperty.routes.js
server/schemas/reportedProperty.schema.js
server/services/reportedProperty.service.js
test/controllers/offer.controller.test.js
test/controllers/property.controller.test.js
test/controllers/reportedProperty.controller.test.js
test/factories/reportedProperty.factory.js
test/helpers.js

Add routes to add, resolve & view reported properties
Add routes to add, resolve & view reported properties
`POST /api/v1/report-property/report`
`PUT /api/v1/report-property/resolve`
`GET /api/v1/report-property/all`
#176955807

#176955807 allow user to report property

---

mailer/index.js
server/controllers/property.controllers.js
server/helpers/filters.js
server/helpers/projectedSchemaInfo.js
server/models/property.model.js
server/routes/property.routes.js
server/schemas/property.schema.js
server/services/property.service.js
server/services/reportedProperty.service.js
test/controllers/property.controller.test.js
test/controllers/reportedProperty.controller.test.js
test/helpers.js
test/services/property.service.test.js

Add route to allow admin flag a reported or suspicious property
Add route to allow admin flag a reported or suspicious property
`POST /api/v1/property/flag`
#176955812

#176955812 admin to flag property

---

mailer/index.js
server/controllers/nextPayment.controllers.js
server/routes/nextPayment.routes.js
server/services/nextPayment.service.js
test/controllers/nextPayment.controller.test.js

Add endpoint to send next payment reminders
Add endpoint to send next payment reminders
`GET /api/v1/next-payment/send-reminders`
#177432169

#177432169 add endpoint to send next payment reminders

---

server/controllers/nextPayment.controllers.js
server/routes/nextPayment.routes.js
server/services/nextPayment.service.js
test/controllers/nextPayment.controller.test.js

Add endpoint to recalculate next payment date for a portfolio
Add endpoint to recalculate next payment date for a portfolio
`GET /api/v1/next-payment/calculate/:id`
#177431788

#177431788 recalculate next payment date for portfolio

---

server/controllers/nextPayment.controllers.js
server/routes/nextPayment.routes.js
server/services/nextPayment.service.js
test/controllers/nextPayment.controller.test.js
test/services/nextPayment.service.test.js

Add route for cronjob to process unresolved expired next payment
Add route for cronjob to process unresolved expired next payment
`GET /api/v1/next-payment/resolved-expired`
#177431721

#177431721 cron job endpoint for next payment

---

server/controllers/property.controllers.js
server/routes/property.routes.js
server/services/property.service.js
test/controllers/property.controller.test.js

Return next payment when viewing portfolio
Return next payment when viewing portfolio
`GET /api/v1/property/:id`
#177431730

#177431730 return next payment when viewing portfolio

---

server/services/nextPayment.service.js
test/controllers/nextPayment.controller.test.js
test/controllers/property.controller.test.js
test/services/nextPayment.service.test.js

The purpose of this PR is to fix the payment schedule bug
* Fix the previous payment schedule bug
* Fix all skipped tests
This can be tested by running the tests `npm test`. If the all tests passes, it means the fix is valid 😅 .

#177621927 Fix payment schedules date

---

server/controllers/offlinePayment.controllers.js
server/helpers/filters.js
server/helpers/middleware.js
server/models/offlinePayment.model.js
server/routes/index.js
server/routes/offlinePayment.routes.js
server/schemas/offlinePayment.schema.js
server/services/offlinePayment.service.js
test/controllers/offlinePayment.controller.test.js
test/factories/offlinePayment.factory.js

Add routes to add and get all offline payments
Add routes to add and get all offline payments
`POST /api/v1/offline-payment`
`PUT /api/v1/offline-payment`
`GET /api/v1/offline-payment/all`
#177431798

#177431798 offline payment confirmation

---

server/services/property.service.js
test/controllers/property.controller.test.js

Fix update neighborhood without map location error
Fix update neighborhood without map location error
`PUT /api/v1/property/:id/neighborhood`
#177638860

#177638860 fix update neighborhood without maplocation error

---

server/services/property.service.js
test/controllers/property.controller.test.js

Return next payment when viewing all portfolios
Return next payment when viewing all portfolios
`GET /api/v1/property/portfolio/all`
#177638855

#177638855 return next payment when viewing all portfolios

---

server/models/user.model.js
server/services/user.service.js
test/controllers/user.controller.test.js

Fix email case insensitivity for login and registration
Fix email case insensitivity for login and registration
`POST /api/v1/user/login`
`POST /api/v1/user/register`
#177638857

#177638857 fix email case insensitivity for login and registration

---

server/controllers/contentProperty.controllers.js
server/helpers/filters.js
server/services/contentProperty.service.js
test/controllers/contentProperty.controller.test.js
test/factories/area.factory.js
test/factories/contentProperty.factory.js

Add filter and sorting to content property
Add filter and sorting to content property
`GET /api/v1/content-property/all`
#177728314

#177728314 add filter and sorting to content property

---

server/controllers/area.controllers.js
server/helpers/filters.js
server/services/area.service.js
test/controllers/area.controller.test.js
test/factories/area.factory.js

Add pagination, filter & sorting to `/api/v1/area/all`
Add pagination, filter & sorting to `/api/v1/area/all`
`GET /api/v1/area/all`
#177728336

#177728336 add pagination, filter & sorting to `/api/v1/area/all`

---

mailer/index.js
server/controllers/offer.controllers.js
server/helpers/constants.js
server/routes/offer.routes.js
server/schemas/offer.schema.js
server/services/offer.service.js
test/controllers/offer.controller.test.js
test/controllers/transaction.controller.test.js
test/services/offer.service.test.js

Add route to allow a vendor to reactivate an expired offer
Add route to allow a vendor to reactivate an expired offer
`PUT /api/v1/offer/reactivate`
#177728201

#177728201 vendor to reactivate expired offer

---

server/controllers/payment.controllers.js
server/schemas/payment.schema.js
server/services/offlinePayment.service.js
server/services/payment.service.js
server/services/transaction.service.js
test/services/offlinePayment.service.test.js

The purpose of this PR is to fix online payment bug
Fix the transaction endpoint to accommodate online payment
This can be tested by using the following endpoint:
- `POST - /api/v1/payment/initiate`
- `GET - /api/v1//verify/:ref`
- `GET - /api/v1/process/:ref`
#177803744

##177803744 Fix online payment bug

---

mailer/index.js
server/controllers/transaction.controllers.js
server/helpers/projectedSchemaInfo.js
server/models/transaction.model.js
server/models/user.model.js
server/routes/transaction.routes.js
server/schemas/helper.schema.js
server/schemas/transaction.schema.js
server/services/transaction.service.js
test/controllers/nextPayment.controller.test.js
test/controllers/transaction.controller.test.js
test/helpers.js

Add remittance to transaction model
Add remittance to transaction model
`PUT /api/v1/transaction/remittance`
#177728140

#177728140 add remittance to transaction model

---

package-lock.json
package.json
server/config/rateLimit.js
server/index.js

Add rate limit to API endpoints
Add rate limit to API endpoints
NA
#177638823

#177638823 add rate limit to API

---

server/controllers/user.controllers.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js

Allows an admin to update a vendor's remittance percentage
Allows an admin to update a vendor's remittance percentage
`PUT /api/v1/user/remittance-percentage`
#177810763

#177810763 admin to update vendor remittance percentage

---

server/services/user.service.js
test/controllers/user.controller.test.js

Load unread notifications to who am I endpoint
Load unread notifications to who am I endpoint
`GET /api/v1/user/who-am-i`
#177913584

#177913584 load unread notifications to who am I endpoint

---

server/services/nextPayment.service.js
server/services/offer.service.js
server/services/property.service.js
server/services/transaction.service.js
server/services/user.service.js
server/services/visitation.service.js
test/helpers.js
test/services/nextPayment.service.test.js
test/services/offer.service.test.js
test/services/property.service.test.js
test/services/transaction.service.test.js
test/services/user.service.test.js
test/services/visitation.service.test.js

Add notifications to services mail is sent
Add notifications to services mail is sent
`npm run test`
#177903406

#177903406 add notifications to services mail is sent

---

server/helpers/notifications.js
server/services/nextPayment.service.js
server/services/offer.service.js
server/services/property.service.js
server/services/transaction.service.js
server/services/user.service.js
server/services/visitation.service.js
test/services/offer.service.test.js
test/services/property.service.test.js
test/services/transaction.service.test.js
test/services/user.service.test.js
test/services/visitation.service.test.js

The purpose of this PR is to fix the notifications bug on the Staging / Production environment. 
Move the notification file into the `servers` so that it can be converted from ES6 to ES6 for production and staging environment.
This can be tested by simulating a production environment on your local machine.
#177977089

#177977089 Fix notifications bug on production

---

server/helpers/projectedSchemaInfo.js
server/services/transaction.service.js
test/controllers/transaction.controller.test.js

Load vendor's remittance percentage for admin
Load vendor's remittance percentage for admin
`GET /api/v1/transaction/all`
`GET /api/v1/transaction/:id`
#178016426

#178016426 load vendor's remittance percentage for admin

---

server/controllers/transaction.controllers.js
server/helpers/filters.js
server/services/transaction.service.js
test/controllers/transaction.controller.test.js

Add sort and filters for `/transaction/all`
Add sort and filters for `/transaction/all`
`GET /api/v1/transaction/all`
#178016456

#178016456 add sort and filters for `/transaction/all`

---

server/controllers/property.controllers.js
server/controllers/transaction.controllers.js
server/controllers/visitation.controllers.js
server/helpers/funtions.js
server/helpers/notifications.js
server/services/enquiry.service.js
server/services/notification.service.js
server/services/offlinePayment.service.js
server/services/transaction.service.js
server/services/user.service.js
server/services/visitation.service.js
test/controllers/notification.controller.test.js
test/controllers/offlinePayment.controller.test.js
test/controllers/transaction.controller.test.js
test/helpers.js
test/services/enquiry.service.test.js
test/services/offlinePayment.service.test.js
test/services/transaction.service.test.js
test/services/user.service.test.js
test/services/visitation.service.test.js

Add non-email notifications
Add non-email notifications
`npm run test`
#178016376

#178016376 add non-email notifications

---

.gitignore
server/controllers/property.controllers.js
server/helpers/filters.js
server/models/property.model.js
server/routes/property.routes.js
server/services/property.service.js
test/controllers/property.controller.test.js

Make admin approve new properties added by vendors
Make admin approve new properties added by vendors
`PUT /api/v1/property/approve/:id`
#178088126

#178088126 make admin approve new properties added by vendors

---

server/services/property.service.js

Add sorting to all `/all` property endpoints
Add sorting to all `/all` property endpoints
`GET /api/v1/property/all`
`GET /api/v1/property/portfolio/all`
#178279133

#178279133 add sorting to all `/all` property endpoints

---

server/services/enquiry.service.js
server/services/offer.service.js
server/services/visitation.service.js

Add sorting to all `/all` pending endpoints
Add sorting to all `/all` pending endpoints
`npm run test`
NA

add sorting to all '/all' pending endpoints

---

mailer/index.js
server/controllers/property.controllers.js
server/helpers/notifications.js
server/routes/property.routes.js
server/services/property.service.js
test/controllers/property.controller.test.js
test/services/property.service.test.js

Add notification and send mail when property is approved
Add notification and send mail when property is approved
`PUT /api/v1/property/approve/:id`
#178279138

#178279138 add notification and send mail when property is approved

---

server/controllers/referral.controllers.js
server/helpers/constants.js
server/models/referral.model.js
server/services/offer.service.js
server/services/referral.service.js
test/controllers/referral.controller.test.js
test/services/offer.service.test.js
test/services/referral.service.test.js

Link offer to referral model when offer is accepted
Link offer to referral model when offer is accepted
`PUT /api/v1/offer/accept`
#178279062

#178279062 link offer to referral model

---

server/helpers/constants.js
server/services/referral.service.js
server/services/transaction.service.js
test/controllers/referral.controller.test.js
test/controllers/transaction.controller.test.js
test/services/referral.service.test.js
test/services/transaction.service.test.js

Update referral status when payment is made
Update referral status when payment is made
`/api/v1/offline-payment/resolve/:id`
#178279081

#178279081 update referral status when payment is made

---

server/controllers/referral.controllers.js
server/helpers/filters.js
server/services/referral.service.js
test/controllers/referral.controller.test.js
test/services/referral.service.test.js

Load appropriate info for getAll referrals
Load appropriate info for getAll referrals
#178279113

#178279113 load appropriate info for getAll referrals

---

server/controllers/referral.controllers.js
server/helpers/projectedSchemaInfo.js
server/routes/referral.routes.js
server/services/referral.service.js
test/controllers/referral.controller.test.js
test/services/referral.service.test.js

Allow all users to view all referrals
Deprecate `GET /api/v1/referral`
#178404047

#178404047 allow all users view all referrals

---

server/services/referral.service.js
test/controllers/referral.controller.test.js

Fix bug that prevents admin from viewing referrals without users
Fix bug that prevents admin from viewing referrals without users
#178426407

#178426407 allow admin view offers without users

---

server/helpers/filters.js
server/models/transaction.model.js
server/services/transaction.service.js
test/controllers/transaction.controller.test.js

Add status to remittance
Add status to remittance
`GET /api/v1/transaction/all`
`POST /api/v1/transaction/remittance`
#178426411

#178426411 add status to remittance

---

test/controllers/referral.controller.test.js

Add tests to confirm admin can view own referrals
Add tests to confirm admin can view own referrals
#178426391

#178426391 add tests to confirm admin can view own referrals

---

server/controllers/property.controllers.js
server/helpers/filters.js
server/helpers/notifications.js
server/models/property.model.js
server/routes/property.routes.js
server/schemas/property.schema.js
server/services/property.service.js
test/controllers/property.controller.test.js
test/services/property.service.test.js

Allow vendor request for property to be unflagged
Allow vendor request for property to be unflagged
`POST /api/v1/property/request-unflag`
#178426404

#178426404 allow vendor request for property to be unflagged

---

server/helpers/filters.js

The purpose of this PR is to add timezone to date filter
- add timezone to date filter
- add timezone to date ranges
- By filtering any of the models by Date
#178512189

#178512189 Add timezone to date filter

---

server/controllers/badge.controllers.js
server/helpers/constants.js
server/helpers/filters.js
server/models/assignedBadge.model.js
server/models/badge.model.js
server/routes/badge.routes.js
server/routes/index.js
server/schemas/badge.schema.js
server/services/assignedBadge.service.js
server/services/badge.service.js
test/controllers/badge.controller.test.js
test/factories/assignedBadge.factory.js
test/factories/badge.factory.js

Add related schema, routes and services for badges
Add related schema, routes, and services for badges
This can be tested by...
#178491462

#178491462 add badges

---

server/controllers/assignedBadge.controllers.js
server/helpers/filters.js
server/models/assignedBadge.model.js
server/routes/assignedBadge.routes.js
server/routes/index.js
server/schemas/assignedBadge.schema.js
server/services/assignedBadge.service.js
server/services/badge.service.js
test/controllers/assignedBadge.controller.test.js

Add assigned badge endpoints
Add assigned badge endpoints
This can be tested by...
#178495535

#178495535 add assigned badge endpoints

---

seeding/defaults.seeding.js
seeding/index.js
seeding/reset.seeding.js
seeding/seed-config.js
seeding/user.seeding.js
server/config/index.js

Restructure seeding process
Restructure seeding process
`npm run seed`
#178564163

#178564163 restructure seeding process

---

mailer/index.js
server/controllers/user.controllers.js
server/helpers/notifications.js
server/routes/user.routes.js
server/services/user.service.js
test/controllers/user.controller.test.js
test/services/user.service.test.js

Allow admin request for users bank details
Allow admin request for users bank details
`POST /api/v1/user/request-bank/:id`
#178601168

#178601168 allow admin request for users bank details

---

server/helpers/projectedSchemaInfo.js
server/services/referral.service.js
test/controllers/referral.controller.test.js

Fix bug allowing referrer see referee details
Fix bug allowing referrer see referee details
#178601160

#178601160 fix getAll referrals endpoint for referrer

---

server/controllers/user.controllers.js
server/routes/user.routes.js
server/schemas/user.schema.js
server/services/user.service.js
test/controllers/user.controller.test.js

Allow users and admin resend activation email
Allow users and admin resend activation email
`POST /api/v1/user/resend-activation/:id`
#178617716

#178617716 allow users and admin resend activation email

---

server/helpers/projectedSchemaInfo.js
server/models/user.model.js
server/schemas/user.schema.js
test/controllers/referral.controller.test.js
test/controllers/user.controller.test.js
test/helpers.js

Add bank details to user model
Add bank details to user model
`PUT /api/v1/user/update`
#178601149

#178601149 add bank details to user model

---

server/models/badge.model.js
server/services/badge.service.js
test/controllers/badge.controller.test.js

Prevent duplicate name for badges
Prevent duplicate name for badges
`POST '/api/v1/badge'`
#178687447

#178687447 prevent duplicate name for badges

---

server/services/user.service.js
test/controllers/user.controller.test.js

Return assigned badges when loading single user
Return assigned badges when loading single user
`GET /api/v1/user/:id`
#178687437

#178687437 return assigned badges when loading single user

---

server/helpers/projectedSchemaInfo.js
server/services/badge.service.js
test/controllers/badge.controller.test.js

Return assigned users when viewing badge
Return assigned users when viewing badge
`GET /api/v1/badge/:id`
`GET /api/v1/badge/all`
#178687463

#178687463 return assigned users when viewing badge

---

server/helpers/funtions.js
server/models/badge.model.js
server/schemas/badge.schema.js
server/services/badge.service.js
test/controllers/badge.controller.test.js
test/factories/badge.factory.js

Add slug and icon to badge
Add slug and icon to badge
`POST /api/v1/badge`
#178703228

#178703228 add slug and icon to badge

---

server/services/totalCount.service.js
test/controllers/totalCount.controller.test.js

Return badges and assigned badges for total count
Return badges and assigned badges for total count
`GET /api/v1/total-count`
#178687444

#178687444 return badges and assigned badges for total count

---

server/helpers/projectedSchemaInfo.js
server/models/referral.model.js
server/services/referral.service.js
server/services/transaction.service.js
test/controllers/referral.controller.test.js
test/controllers/totalCount.controller.test.js
test/services/referral.service.test.js
test/services/transaction.service.test.js

Add accumulated referral to referral model
Add accumulated referral to referral model
NA
#178687478

#178687478 add accumulated referral to referral model

---

server/services/referral.service.js
test/controllers/user.controller.test.js
test/services/user.service.test.js

Referral bonus should be generated from accumulated referral
Referral bonus should be generated from accumulated referral
`GET /api/v1/user/account-overview`
#178769333

#178769333 referral bonus should be generated from accumulated referral

---

server/helpers/automatedBadges.js
server/helpers/filters.js
server/helpers/projectedSchemaInfo.js
server/models/badge.model.js
server/services/assignedBadge.service.js
server/services/badge.service.js
server/services/offer.service.js
server/services/transaction.service.js
server/services/user.service.js
test/controllers/badge.controller.test.js
test/helpers.js
test/services/offlinePayment.service.test.js
test/services/transaction.service.test.js
test/services/user.service.test.js

Add automated badges
Add automated badges
NA
#178703269

#178703269 add automated badges

---

server/services/assignedBadge.service.js
test/controllers/assignedBadge.controller.test.js

Ensure admin cannot assign automated badges
Ensure admin cannot assign automated badges
`POST /api/v1/assign-badge`
#178769391

#178769391 ensure admin cannot assign automated badges

---

seeding/defaults.seeding.js
seeding/index.js
seeding/property.seeding.js
seeding/seed-constants.js
seeding/seed-helpers.js

Create seeding for properties
Create seeding for properties
`npm run test`
#178088003

#178088003 create seeding for properties

---

server/controllers/badge.controllers.js
server/helpers/middleware.js
server/routes/badge.routes.js
server/schemas/badge.schema.js
server/services/badge.service.js
test/controllers/badge.controller.test.js

Create endpoint to return all badges and role-specific badges
Create endpoint to return all badges and role-specific badges
`POST /api/v1/badge/role-specific`
#178769403

#178769403 create endpoint to return all badges and role specific badges

---

server/helpers/projectedSchemaInfo.js

Include role in projected user values
Make role projected when projecting user values
NA
#178877471

#178877471 include role in projected user values

---

server/controllers/bankAccount.controllers.js
server/helpers/filters.js
server/models/bankAccount.model.js
server/routes/bankAccount.routes.js
server/routes/index.js
server/schemas/bankAccount.schema.js
server/services/bankAccount.service.js
server/services/offer.service.js
test/controllers/bankAccount.controller.test.js
test/factories/bankAccount.factory.js

Add bank account model 
Add bank account model to cater to updated offer model
`POST /api/v1/bank-account`
`PUT /api/v1/bank-account`
`PUT /api/v1/bank-account/approve/:id`
`DELETE /api/v1/bank-account/:id`
`GET /api/v1/bank-account/all`
#178875360

#178875360 add bank account model
